1: 1.c
	@echo "Program to implement DFA for language of string over {0,1} in which each string ends with '11'"
	@echo "Author: Jivan Parajuli"
	@gcc -o bin/1.exe 1.c && bin/1.exe
2: 2.c
	@echo "Program implementing DFA accepting the string over {a,b} such that each string does not end with ab"
	@echo "Author: Jivan Parajuli"
	@gcc -o bin/2.exe 2.c && bin/2.exe
3: 3.c	
	@echo "Program implementing DFA for the language of string {a,b} such that each string contains aba as substring"
	@echo "Author: Jivan Parajuli"
	@gcc -o bin/3.exe 3.c && bin/3.exe