1:
	@echo "Program to simulate a NFA that accepts string ends with 10"
	@echo "Author: Jivan Parajuli"
	@gcc 1.c -o bin/1 && ./bin/1

2:
	@echo "Program to simulate a NFA that accepts string that starts with 01"
	@echo "Author: Jivan Parajuli"
	@gcc 2.c -o bin/2 && ./bin/2

3:
	@echo "Program to simulate a NFA that accepts string that contains substring 010"
	@echo "Author: Jivan Parajuli"
	@gcc 3.c -o bin/3 && ./bin/3